---

- name: Install  openssl
  become: yes
  apt: 
      name: openssl 
      state: present


- name: create certificates directory
  become: yes
  file:
    path:  /etc/nginx/ssl/
    state: directory
    group: ubuntu
    owner: ubuntu

- name : create ssl certificates
  become: yes
  shell: |
     openssl req -new -nodes -x509 -subj "/CN=testingin" -days 365 -keyout /etc/nginx/ssl/server.key -out /etc/nginx/ssl/server.crt -extensions v3_ca
  args:
    executable: /bin/bash





